packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  "typescript": ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: ^0.2.4
  sass: ^1.101.0
  vitepress: "^2.0.0-alpha.17"
  typedoc: ^0.28.19
  typedoc-plugin-markdown: ^4.12.0
  typedoc-vitepress-theme: ^1.1.3
  vitepress-sidebar: ^1.36.1
  oxc-minify: ^0.138.0
  bumpp: ^11.1.0
  vite-plugin-dts: ^5.0.3
  pino: ^10.3.1
  dexie: ^4.4.4
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  "@parcel/watcher": set this to true or false
  "@vaadin/vaadin-usage-statistics": false
patchedDependencies:
  '@vaadin/vaadin-usage-statistics': patches/@vaadin__vaadin-usage-statistics.patch
